### ISSUE TITLE
License issue?

### ISSUE THREAD

**Issue by dietmarw** [physiology/Physiomodel#2]
According to the README Physiomodel is based on HumMod(licensed partly under GPL 2.0 and partly no license but special agreement)  and Physiolibrary (BSD).

Since you don't specify what license agreement _you_ have with the HumMod project it is the case that your GPL3.0 license is simply not compatible with the HumMod part **except** you got a special GPL3.0  compliant license agreement. But this I doubt since is most likely not the case. (Imagine that then people would simply use your GPL3.0 HumMod parts rather then trying to get an agreement with HumMod directly). GPL2.0 is btw **not** compatible with GPL3.0 unless a project is licensed GPL2.0 **and later** (which I could not find on the GPL2.0 part of HumMod).

So you might wanna revisit the licensing issue and straighten things out ;-)

**Comment by MarekMatejak** [comment]
The Physiomodel does not contains any line of source code from HumMod, but it uses the "know-how" from it. This is the meaning of "is based on HumMod". I do not thing, that these software licences works also in this way. However the meaning "is based on Physiolibrary" really means that it uses Physiolibrary 2.3.1 as it is, so there should not be the problem with using BSD source code in GPL3.0 source code. The link to HumMod is important, because without the cooperation with Mississippi University and HC Simulation, LLC and without using this "know-how" it wouldn't be possible to create Physiomodel. In future, we have a plan to make similar business model as OpenModelica do with Consortium (under Charles University and UMMC).

**Comment by dietmarw** [comment]
OK. Then I guess it is fine. The BSD part into GPL code is fine too. I was, as you pointed out, misunderstanding the "based on" part.

**Comment by drew-pruett** [comment]
I'm not sure the lawyers would agree on that read.

Sent from my iPhone

On Oct 28, 2015, at 8:22 AM, Dietmar Winkler <notifications@github.com<mailto:notifications@github.com>> wrote:

OK. Then I guess it is fine. The BSD part into GPL code is fine too. I was, as you pointed out, misunderstanding the "based on" part.

—
Reply to this email directly or view it on GitHubhttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_physiology_Physiomodel_issues_2-23issuecomment-2D151843414&d=CwMCaQ&c=lsRuZCBl6GuC9L6xVrEM6HFPHJkrlPlfLCjYs_lBYHk&r=a2eAR7jIO0_7euyoZP3hCQ&m=c8qHp7NJzVGHrK8qxHMiwNFHEx4_PGo8C3ZvQLygLwI&s=g-FAG5eOxLNAnuv6rPTX6XSGmWtPqFVPs2IXfRCo1B0&e=.

Individuals who have received this information in error or are not authorized to receive it must promptly return or dispose of the information and notify the sender. Those individuals are hereby notified that they are strictly prohibited from reviewing, forwarding, printing, copying, distributing or using this information in any way.
